/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vscode_intellisense_issue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        String line = classUnderTest.someLibraryMethod("abc");
        assertFalse(line.isEmpty());
    }
}
